version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
    - dependencies
    - govuk-pay
    - docker
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 0
  labels:
  - dependencies
  - govuk-pay
  - github_actions
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  labels:
  - dependencies
  - govuk-pay
  - gomod
  open-pull-requests-limit: 0
